### ISSUE TITLE
前端为多用户操作还是单用户操作？

### ISSUE THREAD

**Issue by BarrinXu** [oscardhc/TicketSystem-2020#3]
在后端的接口中，允许多个用户登录到系统，那么在前端的网页实现中，是否也要实现多个用户同时登录的功能？还是按照正常的账户惯例，一次只能登录一个用户？

**Comment by oscardhc** [comment]
每一个前端客户端都可以登录一个用户，可以有很多前端同时打开，且它们的登录状态可以共存（这也就是为什么当前用户列表是一个集合而不是某个特定的用户了）。
对后端来讲，不同前端发送命令的-c或-u不同，因此对于一个前端只需要判断当前登录的是哪【一个】用户，并且把这个信息作为指令的操作者告诉后端就好了。

**Comment by BarrinXu** [comment]
懂了，谢谢寒菜哥哥！
